services:
  api:
    image: daandewilde/mlops-exam-1-backend:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8181:8181"

  # create a new service called forntend
  frontend:
    depends_on:
      - api
    image: daandewilde/mlops-exam-1-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    
