apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-daandewilde
  labels:
    exam: version1
    app: nginx-daandewilde-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-daandewilde-app
  template:
    metadata:
      labels:
        app: nginx-daandewilde-app
    spec:
      containers:
      - name: nginx-daandewilde-app
        image: nathansegers/vue-docker:2.0.0
        ports:
        - containerPort: 80
      restartPolicy: Always