apiVersion: v1
kind: Service
metadata:
  name: mlops-exam-1-backend-svc
spec:
  selector:
    app.kubernetes.io/name: mlops-exam-1-backend-dpl
  ports:
    - protocol: TCP
      port: 30001
      targetPort: 8181