apiVersion: v1
kind: Service
metadata:
  name: mlops-exam-1-frontend-svc
spec:
  selector:
    app.kubernetes.io/name: mlops-exam-1-frontend-dpl
  ports:
    - protocol: TCP
      port: 30000
      targetPort: 8080