name: MLOps Automation

on:
  push:
    branches: [ main ]

jobs:
  start:
    uses: ./.github/workflows/azure-ai.yml
    with:
      data_prep: false
      process_images: false
      ai_training: false
      train_on_local: false
      api_creation: false
      create_docker_image: false
      azure_deployment: false
      remove_deployment: false
      docker_deployment: false
      kubernetis_deployment: false
    secrets: inherit